apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-simple-web-app
  labels:
    app: simple-web-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: simple-web-app
  template:
    metadata:
      labels:
        app: simple-web-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8887
              protocol: TCP