replicaCount: 2

image:
  repository: registry.sighup.io/devsecopsday/app
  tag: "prod"
  pullPolicy: IfNotPresent

service:
  name: simple-web-app-service
  type: ClusterIP
  port: 80
  targetPort: 8887

env:
  name: dev
